source "https://rubygems.org"

gem "jekyll", "~> 4.3"

# Windows/JRuby builds don't ship zoneinfo data or a native file-watcher.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end
