/*
 * THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @clew homepage: https://ariadne-thread.io
 * @clew connector-type: req-as-code
 * @clew generator-type: typescript
 */

import { ArchTraceables } from './ArchTraceables.js';
import { ConTraceables } from './ConTraceables.js';
import { SwTraceables } from './SwTraceables.js';
import { SysTraceables } from './SysTraceables.js';

export { ArchTraceables, ConTraceables, SwTraceables, SysTraceables };

export type TraceableId =
  ArchTraceables | ConTraceables | SwTraceables | SysTraceables;

/** A single id, or a non-empty list of ids — an anchor must name at least one spec. */
export type TraceableIds =
  TraceableId | readonly [TraceableId, ...TraceableId[]];

// The three relations and every marker form are documented in the README.md
// in this folder.

/**
 * Marks a type or interface as **realizing** one or more spec ids; the type is unchanged.
 *
 * @example
 * type AnchoredState = Realizes<ArchTraceables.ARCH_001_ITEM_TABLES_PUBLIC_WITH_CLIENT_SIDE_OWNERSHIP_FILTER, { sequences: number[] }>;
 *
 * @example
 * interface IdStrategy extends Realizes<ArchTraceables.ARCH_001_ITEM_TABLES_PUBLIC_WITH_CLIENT_SIDE_OWNERSHIP_FILTER, {}> { mint(): void; }
 */
export type Realizes<Id extends TraceableIds, T> = T & {
  readonly __realizes?: Id;
};

/**
 * Marks a type or interface as **concerning** one or more spec ids — coupled to
 * the spec without realizing it; the type is unchanged.
 *
 * @example
 * interface IdStrategy extends Concerns<ArchTraceables.ARCH_001_ITEM_TABLES_PUBLIC_WITH_CLIENT_SIDE_OWNERSHIP_FILTER, {}> { mint(): void; }
 */
export type Concerns<Id extends TraceableIds, T> = T & {
  readonly __concerns?: Id;
};

/**
 * Anchors code that **realizes** one or more spec ids; a removed id fails to compile.
 *
 * Called with a value it returns the value unchanged (wrap a function or
 * constant). Called with only the ids it returns a no-op decorator (annotate a
 * class or method).
 *
 * @example
 * export const mint = realizes(ArchTraceables.ARCH_001_ITEM_TABLES_PUBLIC_WITH_CLIENT_SIDE_OWNERSHIP_FILTER, (type: string, count: number): string[] => []);
 *
 * @example
 * class Minter { @realizes(ArchTraceables.ARCH_001_ITEM_TABLES_PUBLIC_WITH_CLIENT_SIDE_OWNERSHIP_FILTER) mint() {} }
 */
export function realizes<Value>(ids: TraceableIds, value: Value): Value;
export function realizes(
  ids: TraceableIds,
): (target: unknown, propertyKey?: unknown, descriptor?: unknown) => void;
export function realizes(_ids: TraceableIds, ...rest: unknown[]): unknown {
  if (rest.length === 1) {
    return rest[0];
  }
  return () => {};
}

/**
 * Anchors code that **concerns** one or more spec ids — coupled to the spec
 * without realizing or verifying it; a removed id fails to compile.
 *
 * Same two forms as `realizes`: a value or function wrapper, or — called with
 * only the ids — a no-op class/method decorator. The anchor is existence-checked
 * only; nothing exercises it (ADR-0004).
 *
 * @example
 * export const render = concerns(ArchTraceables.ARCH_001_ITEM_TABLES_PUBLIC_WITH_CLIENT_SIDE_OWNERSHIP_FILTER, (n: number): string => String(n));
 *
 * @example
 * class Minter { @concerns(ArchTraceables.ARCH_001_ITEM_TABLES_PUBLIC_WITH_CLIENT_SIDE_OWNERSHIP_FILTER) render() {} }
 */
export function concerns<Value>(ids: TraceableIds, value: Value): Value;
export function concerns(
  ids: TraceableIds,
): (target: unknown, propertyKey?: unknown, descriptor?: unknown) => void;
export function concerns(_ids: TraceableIds, ...rest: unknown[]): unknown {
  if (rest.length === 1) {
    return rest[0];
  }
  return () => {};
}

/**
 * Anchors a test that **verifies** one or more spec ids and runs it unchanged.
 *
 * @example
 * verifies(ArchTraceables.ARCH_001_ITEM_TABLES_PUBLIC_WITH_CLIENT_SIDE_OWNERSHIP_FILTER, () => { test("holds", () => {}); });
 */
export function verifies(ids: TraceableIds, run: () => void): void {
  run();
}
