name: Build & Test

on:
  push:
    branches:
      - '**'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run prettier:check
      - run: pnpm run build
